# Generated by Django 3.2.6 on 2021-08-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('custname', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('bal', models.CharField(max_length=50)),
            ],
        ),
    ]
