# Generated by Django 3.2.6 on 2021-09-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoizFonica', '0007_alter_dongle_typeofservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prepaidinvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobno', models.CharField(max_length=25)),
                ('typeservices', models.CharField(max_length=50)),
                ('pname', models.CharField(max_length=50)),
                ('pamount', models.CharField(max_length=50)),
                ('paymentmethod', models.CharField(max_length=50)),
                ('curdate', models.CharField(default='09/09/2021 17:33:23', max_length=50)),
            ],
        ),
    ]
