# Generated by Django 3.2.6 on 2021-09-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoizFonica', '0008_prepaidinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidinvoice',
            name='curdate',
            field=models.CharField(default='14/09/2021 12:07:31', max_length=50),
        ),
        migrations.AlterField(
            model_name='queries',
            name='querysolution',
            field=models.CharField(default='', max_length=50),
        ),
    ]
