# Generated by Django 3.2.7 on 2021-09-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoizFonica', '0009_auto_20210914_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidinvoice',
            name='curdate',
            field=models.CharField(default='14/09/2021 23:17:00', max_length=50),
        ),
    ]
