# Generated by Django 3.2.6 on 2021-09-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoizFonica', '0010_alter_prepaidinvoice_curdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=50)),
                ('curplancharge', models.CharField(max_length=50)),
                ('extracallcharge', models.CharField(max_length=50)),
                ('extrasmscharge', models.CharField(max_length=50)),
                ('extradatacharges', models.CharField(max_length=50)),
                ('totalamount', models.CharField(default=True, max_length=50)),
                ('currdate', models.CharField(default='15/09/2021 11:04:55', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobilen', models.CharField(default=True, max_length=50)),
                ('curplan', models.CharField(default=True, max_length=50)),
                ('extracall', models.CharField(default=True, max_length=50)),
                ('extrasms', models.CharField(default=True, max_length=50)),
                ('extradata', models.CharField(default=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='prepaidinvoice',
            name='curdate',
            field=models.CharField(default='15/09/2021 11:04:55', max_length=50),
        ),
    ]
