# Generated by Django 3.2.6 on 2021-08-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('pcode', models.IntegerField()),
                ('pdescp', models.CharField(max_length=50)),
                ('pprice', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Productapplication',
        ),
    ]
