# Generated by Django 3.2.6 on 2021-08-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('sid', models.IntegerField()),
                ('sadd', models.CharField(max_length=50)),
                ('sphone', models.CharField(max_length=50)),
            ],
        ),
    ]
